<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ekamban-Laptop" failures="2" tests="2" name="Test" time="43.706" errors="0" timestamp="2020-09-08T13:16:07 NZST">
  <testcase classname="TP.E2ESelenium.ValidateTest" name="homepagenaviagation" time="9.002">
    <failure type="java.lang.AssertionError" message="expected [There is 1 erro] but found [There is 1 error]">
      <![CDATA[java.lang.AssertionError: expected [There is 1 erro] but found [There is 1 error]
at TP.E2ESelenium.ValidateTest.homepagenaviagation(ValidateTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- homepagenaviagation -->
  <testcase classname="TP.E2ESelenium.ValidateTest" name="homepagenaviagation" time="9.225">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at resources.baseclass.getScreenShotPath(baseclass.java:51)
at TP.E2ESelenium.Listeners.onTestFailure(Listeners.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- homepagenaviagation -->
</testsuite> <!-- Test -->
